/*export const StandardProducts = {
  ELECTRONICS: 'ELECTRONICS',
  CHEMICALS: 'CHEMICALS',
  BATTERIES: 'BATTERIES',
  PAINT: 'PAINT',
  METAL_SCRAP: 'METAL_SCRAP',
  PLASTIC: 'PLASTIC',
  PAPER: 'PAPER',
  GLASS: 'GLASS',
  ORGANIC_WASTE: 'ORGANIC_WASTE',
  CONSTRUCTION_DEBRIS: 'CONSTRUCTION_DEBRIS',
  OTHER: 'OTHER'
}; */